# Site
name: "1인개발자 LR의 IT블로그"
title: "1인개발자 LR의 IT블로그"
description: "대학생 1인 개발자의 험난한 앱개발 여정"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/'
url: 'https://blog-lr.defcon.or.kr'
disqus: 'blog-lr-defcon-or-kr'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  LR:
    name: Dev. LR
    display_name: LR
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: yymin1022@gmail.com
    web: https://defcon.or.kr
    twitter: https://twitter.com/yymin1022  
    description: "중앙대학교 소프트웨어학부 19학번 / 대학생 1인 개발자 / 대한민국 공군 ROKAF 체계운영병"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
